### PR TITLE
add hand velocity

### PR DESCRIPTION
**Pull request by lorak41**
I am trying to make objects throwable in MRTK using Quest. After trying lots of different implementations I decided to copy the function from BaseHand.cs. Linear velocity works nicely, but there is still problem with AngularVelocity. I hope someone can help to solve this issue.

### CODE REVIEW

**Comment by provencher** [comment]
Referencing issue #23.

**Comment by lorak41** [comment]
Update. This implementation is working fine. The problem is most probably with the Object Manipulator in MRTK

**Comment by lorak41** [comment]
I think it can be merged now

**Comment by provencher** [comment]
Looks great!

**Pull request merged**
